spring:
  application:
    name: ConstructorService
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

okta:
  oauth2:
    issuer: ${OKTA_API_ISSUER}
    audience: ${OKTA_API_AUDIENCE}

openapi:
  service:
    title: ConstructorService
    version: 1.0.0
    url: ${OPENAPI_URL}
springdoc:
  api-docs:
    path: /constructorservice/api-docs
  swagger-ui:
    path: /constructorservice/swagger-ui

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
    healthcheck:
      enabled: true