server:
  port: ${PORT:8080}

spring:
  application:
    name: ChatService
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    hikari:
      maximum-pool-size: ${HIKARI_MAX_POOL_SIZE:10}
      minimum-idle: ${HIKARI_MINIMUM_IDLE:10}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}

broker:
  relay:
    host: ${RABBITMQ_HOST:localhost}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}

okta:
  oauth2:
    issuer: ${OKTA_API_ISSUER}
    audience: ${OKTA_API_AUDIENCE}

cloudinary:
  api-key: ${CLOUDINARY_API_KEY}
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-secret: ${CLOUDINARY_API_SECRET}
  folder-name: ${CLOUDINARY_FOLDER_NAME}

feign:
  client:
    urls:
      UserService: ${FEIGN_URL_USERSERVICE:}

openapi:
  service:
    title: ChatService
    version: 1.0.0
    url: ${OPENAPI_URL}
springdoc:
  api-docs:
    path: /chatservice/api-docs
  swagger-ui:
    path: /chatservice/swagger-ui

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
    healthcheck:
      enabled: true