server:
  port: 8080
  error:
    include-message: always

spring:
  application:
    name: ApiGateway
  data:
    redis:
      database: 0
      host: localhost
      port: 6380
      password: ${REDIS_PASSWORD_APIGATEWAY}
      connect-timeout: 60000
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin, RETAIN_UNIQUE
        - AddResponseHeader=Access-Control-Allow-Origin, *
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173, http://127.0.0.1:5173"
            allowedHeaders: "*"
            allowCredentials: true
            allowedMethods: "*"

eureka:
  client:
    service-url:
      defaultZone: http://homeo-eureka:8761/eureka

logging:
  level:
    org.springframework.security: DEBUG

springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui
    urls:
      - url: /api-docs
        name: API Gateway Service
      - url: /userservice/api-docs
        name: User Service
