server:
  port: ${PORT:8080}

spring:
  application:
    name: ApiGateway
  data:
    redis:
      database: 0
      host: ${REDIS_HOST_APIGATEWAY:localhost}
      port: ${REDIS_PORT_APIGATEWAY:6380}
      password: ${REDIS_PASSWORD_APIGATEWAY}
      connect-timeout: 60000
      username: ${REDIS_USERNAME_APIGATEWAY:}
      ssl:
        enabled: ${REDIS_SSL_APIGATEWAY:false}
  cloud:
    gateway:
      httpclient:
        websocket:
          max-frame-payload-length: 5242880 # 5MB
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin, RETAIN_UNIQUE
        - AddResponseHeader=Access-Control-Allow-Origin, *
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: ${ALLOWED_CORS_URLS}
            allowedHeaders: "*"
            allowCredentials: true
            allowedMethods: "*"

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
    path: /api/api-docs
  swagger-ui:
    enabled: true
    path: /api/swagger-ui
    urls:
      - url: /api/api-docs
        name: ApiGateway
      - url: /api/userservice/api-docs
        name: UserService
      - url: /api/constructorservice/api-docs
        name: ConstructorService
      - url: /api/reviewservice/api-docs
        name: ReviewService
      - url: /api/searchservice/api-docs
        name: SearchService
      - url: /api/chatservice/api-docs
        name: ChatService
