server:
  port: 8080
  error:
    include-message: always

spring:
  application:
    name: ApiGateway
  data:
    redis:
      database: 0
      host: localhost
      port: 6380
      password: ${REDIS_PASSWORD_APIGATEWAY}
      connect-timeout: 60000
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"

eureka:
  client:
    service-url:
      defaultZone: http://homeo-eureka:8761/eureka

logging:
  level:
    org.springframework.security: DEBUG

springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui
    urls:
      - url: /api-docs
        name: API Gateway Service
      - url: /userservice/api-docs
        name: User Service
