server:
  port: ${PORT:8080}

spring:
  application:
    name: ApiGateway
  data:
    redis:
      database: 0
      host: ${REDIS_HOST_APIGATEWAY:localhost}
      port: ${REDIS_PORT_APIGATEWAY:6380}
      password: ${REDIS_PASSWORD_APIGATEWAY}
      connect-timeout: 60000
      username: ${REDIS_USERNAME_APIGATEWAY:}
      ssl:
        enabled: ${REDIS_SSL_APIGATEWAY:false}
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin, RETAIN_UNIQUE
        - AddResponseHeader=Access-Control-Allow-Origin, *
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: ${ALLOWED_CORS_URLS}
            allowedHeaders: "*"
            allowCredentials: true
            allowedMethods: "*"

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}

springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui
    urls:
      - url: /api-docs
        name: API Gateway Service
      - url: /userservice/api-docs
        name: User Service
      - url: /constructorservice/api-docs
        name: ConstructorService
      - url: /reviewservice/api-docs
        name: ReviewService
      - url: /searchservcice/api-docs
        name: SearchService
