version: "3.8"

services:
  homeo-userservice:
    container_name: homeo-userservice
    build: ../../UserService
    environment:
      PORT: ${PORT_USERSERVICE}
      HIKARI_MAX_POOL_SIZE: ${HIKARI_MAX_POOL_SIZE_USERSERVICE}
      HIKARI_MINIMUM_IDLE: ${HIKARI_MINIMUM_IDLE_USERSERVICE}
      OKTA_API_ISSUER: ${OKTA_API_ISSUER}
      OKTA_API_AUDIENCE: ${OKTA_API_AUDIENCE}
      OKTA_API_DOMAIN: ${OKTA_API_DOMAIN}
      OKTA_MTM_CLIENT_ID: ${OKTA_MTM_CLIENT_ID}
      OKTA_MTM_CLIENT_SECRET: ${OKTA_MTM_CLIENT_SECRET}
      OKTA_MANAGEMENT_API_AUDIENCE: ${OKTA_MANAGEMENT_API_AUDIENCE}
      OKTA_AUTH0_USER_ROLE_ID: ${OKTA_AUTH0_USER_ROLE_ID}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_URL: ${POSTGRES_URL_USERSERVICE}
      EUREKA_URL: ${EUREKA_URL}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
      CLOUDINARY_FOLDER_NAME: ${CLOUDINARY_FOLDER_NAME_USERSERVICE}
      CLOUDINARY_DEFAULT_AVATAR_URL: ${CLOUDINARY_DEFAULT_AVATAR_URL}
      OPENAPI_URL: ${OPENAPI_URL}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
    ports:
      - "${PORT_USERSERVICE}:${PORT_USERSERVICE}"
    restart: unless-stopped
    depends_on:
      - homeo-apigateway

  homeo-constructorservice:
    container_name: homeo-constructorservice
    build: ../../ConstructorService
    environment:
      PORT: ${PORT_CONSTRUCTORSERVICE}
      HIKARI_MAX_POOL_SIZE: ${HIKARI_MAX_POOL_SIZE_CONSTRUCTORSERVICE}
      HIKARI_MINIMUM_IDLE: ${HIKARI_MINIMUM_IDLE_CONSTRUCTORSERVICE}
      OKTA_API_ISSUER: ${OKTA_API_ISSUER}
      OKTA_API_AUDIENCE: ${OKTA_API_AUDIENCE}
      OKTA_API_DOMAIN: ${OKTA_API_DOMAIN}
      OKTA_MTM_CLIENT_ID: ${OKTA_MTM_CLIENT_ID}
      OKTA_MTM_CLIENT_SECRET: ${OKTA_MTM_CLIENT_SECRET}
      OKTA_MANAGEMENT_API_AUDIENCE: ${OKTA_MANAGEMENT_API_AUDIENCE}
      OKTA_AUTH0_CONSTRUCTOR_ROLE_ID: ${OKTA_AUTH0_CONSTRUCTOR_ROLE_ID}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_URL: ${POSTGRES_URL_CONSTRUCTORSERVICE}
      EUREKA_URL: ${EUREKA_URL}
      OPENAPI_URL: ${OPENAPI_URL}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
      CLOUDINARY_FOLDER_NAME: ${CLOUDINARY_FOLDER_NAME_USERSERVICE}
      CLOUDINARY_DEFAULT_CATEGORY_URL: ${CLOUDINARY_DEFAULT_CATEGORY_URL}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      API_NINJAS_URL: ${API_NINJAS_URL}
      API_NINJAS_KEY: ${API_NINJAS_KEY}
    ports:
      - "${PORT_CONSTRUCTORSERVICE}:${PORT_CONSTRUCTORSERVICE}"
    restart: unless-stopped
    depends_on:
      - homeo-userservice

  homeo-reviewservice:
    container_name: homeo-reviewservice
    build: ../../ReviewService
    environment:
      PORT: ${PORT_REVIEWSERVICE}
      HIKARI_MAX_POOL_SIZE: ${HIKARI_MAX_POOL_SIZE_REVIEWSERVICE}
      HIKARI_MINIMUM_IDLE: ${HIKARI_MINIMUM_IDLE_REVIEWSERVICE}
      OKTA_API_ISSUER: ${OKTA_API_ISSUER}
      OKTA_API_AUDIENCE: ${OKTA_API_AUDIENCE}
      OKTA_API_DOMAIN: ${OKTA_API_DOMAIN}
      OKTA_MTM_CLIENT_ID: ${OKTA_MTM_CLIENT_ID}
      OKTA_MTM_CLIENT_SECRET: ${OKTA_MTM_CLIENT_SECRET}
      OKTA_MANAGEMENT_API_AUDIENCE: ${OKTA_MANAGEMENT_API_AUDIENCE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_URL: ${POSTGRES_URL_REVIEWSERVICE}
      EUREKA_URL: ${EUREKA_URL}
      OPENAPI_URL: ${OPENAPI_URL}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
    ports:
      - "${PORT_REVIEWSERVICE}:${PORT_REVIEWSERVICE}"
    restart: unless-stopped
    depends_on:
      - homeo-constructorservice

  homeo-searchservice:
    container_name: homeo-searchservice
    build: ../../SearchService
    environment:
      PORT: ${PORT_SEARCHSERVICE}
      HIKARI_MAX_POOL_SIZE: ${HIKARI_MAX_POOL_SIZE_SEARCHSERVICE}
      HIKARI_MINIMUM_IDLE: ${HIKARI_MINIMUM_IDLE_SEARCHSERVICE}
      OKTA_API_ISSUER: ${OKTA_API_ISSUER}
      OKTA_API_AUDIENCE: ${OKTA_API_AUDIENCE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_URL: ${POSTGRES_URL_SEARCHSERVICE}
      EUREKA_URL: ${EUREKA_URL}
      OPENAPI_URL: ${OPENAPI_URL}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
    ports:
      - "${PORT_SEARCHSERVICE}:${PORT_SEARCHSERVICE}"
    restart: unless-stopped
    depends_on:
      - homeo-reviewservice

  homeo-apigateway:
    container_name: homeo-apigateway
    build: ../../ApiGateway
    environment:
      EUREKA_URL: ${EUREKA_URL}
      REDIS_PASSWORD_APIGATEWAY: ${REDIS_PASSWORD_APIGATEWAY}
      REDIS_PORT_APIGATEWAY: ${REDIS_PORT_APIGATEWAY}
      REDIS_HOST_APIGATEWAY: ${REDIS_HOST_APIGATEWAY}
      REDIS_USERNAME_APIGATEWAY: ${REDIS_USERNAME_APIGATEWAY}
      REDIS_SSL_APIGATEWAY: ${REDIS_SSL_APIGATEWAY}
      ALLOWED_CORS_URLS: ${ALLOWED_CORS_URLS}
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - homeo-eureka

  homeo-eureka:
    container_name: homeo-eureka
    build: ../../Eureka
    ports:
      - "8761:8761"
    restart: unless-stopped

  homeo-rabbit:
    container_name: homeo-rabbit
    build: RabbitMQ/
    environment:
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
    volumes:
      - homeo-rabbit:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  homeo-rabbit:
