server:
  port: ${PORT:8761}

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
  metrics:
    tags:
      application: Eureka

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
