server:
  port: ${PORT:8761}

spring:
  application:
    name: Eureka

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
