server:
  port: ${PORT:8080}

spring:
  application:
    name: UserService
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    hikari:
      maximum-pool-size: ${HIKARI_MAX_POOL_SIZE:10}
      minimum-idle: ${HIKARI_MINIMUM_IDLE:10}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}

okta:
  oauth2:
    issuer: ${OKTA_API_ISSUER}
    audience: ${OKTA_API_AUDIENCE}
  sdk:
    domain: ${OKTA_API_DOMAIN}
    client-id: ${OKTA_MTM_CLIENT_ID}
    client-secret: ${OKTA_MTM_CLIENT_SECRET}
    audience: ${OKTA_MANAGEMENT_API_AUDIENCE}
  auth0:
    roles:
      user-role-id: ${OKTA_AUTH0_USER_ROLE_ID}

cloudinary:
  api-key: ${CLOUDINARY_API_KEY}
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-secret: ${CLOUDINARY_API_SECRET}
  folder-name: ${CLOUDINARY_FOLDER_NAME}
  default-avatar: ${CLOUDINARY_DEFAULT_AVATAR_URL}

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

openapi:
  service:
    title: ${spring.application.name}
    version: 1.0.0
    url: ${OPENAPI_URL}
springdoc:
  api-docs:
    path: /userservice/api-docs
  swagger-ui:
    path: /userservice/swagger-ui

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
    healthcheck:
      enabled: true
