spring:
  application:
    name: UserService
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

okta:
  oauth2:
    issuer: ${OKTA_API_ISSUER}
    audience: ${OKTA_API_AUDIENCE}
  sdk:
    domain: ${OKTA_API_DOMAIN}
    client-id: ${OKTA_MTM_CLIENT_ID}
    client-secret: ${OKTA_MTM_CLIENT_SECRET}
    audience: ${OKTA_MANAGEMENT_API_AUDIENCE}
  auth0:
    roles:
      constructor-role-id: rol_UCL6ZThu4ydr1nYW

cloudinary:
  api-key: ${CLOUDINARY_API_KEY}
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-secret: ${CLOUDINARY_API_SECRET}
  folder-name: homeo/userservice
  default-avatar: https://res.cloudinary.com/dyihgedrz/image/upload/v1709401307/homeo/ddvvvusgqhkga3iimm4q.jpg

openapi:
  service:
    title: UserService
    version: 1.0.0
    url: http://localhost:8080
springdoc:
  api-docs:
    path: /userservice/api-docs
  swagger-ui:
    path: /userservice/swagger-ui

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
