version: "3.8"

services:
  homeo-userservice:
    container_name: homeo-userservice
    build: ../UserService
    ports:
      - 8081:8081
    restart: unless-stopped
    depends_on:
      - homeo-apigateway

  homeo-apigateway:
    container_name: homeo-apigateway
    build: ../ApiGateway
    ports:
      - 8080:8080
    restart: unless-stopped
    depends_on:
      - homeo-eureka

  homeo-eureka:
    container_name: homeo-eureka
    build: ../Eureka
    ports:
      - 8761:8761
    restart: unless-stopped

  homeo-postgres:
    container_name: homeo-postgres
    build: ../Postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: ${PGDATA}
    volumes:
      - homeo-postgres:/data/homeo-postgres
    ports:
      - 5432:5432
    restart: unless-stopped

  homeo-keycloak:
    image: quay.io/keycloak/keycloak:22.0.4
    container_name: homeo-keycloak
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: ${KC_DB}
      KC_DB_URL_HOST: ${KC_DB_URL_HOST}
      KC_DB_URL_DATABASE: ${KC_DB_URL_DATABASE}
      KC_DB_USERNAME: ${KC_DB_USERNAME}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
    ports:
      - 8079:8080
    command: start-dev
    depends_on:
      - homeo-postgres

volumes:
  homeo-postgres:
