version: "3.8"

services:
  homeo-eureka:
    container_name: homeo-eureka
    build: ../Eureka
    ports:
      - 8761:8761
    restart: unless-stopped

  homeo-postgres:
    container_name: homeo-postgres
    build: ../Postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /data/homeo-postgres
    volumes:
      - homeo-postgres:/data/homeo-postgres
    ports:
      - 5432:5432
    restart: unless-stopped

  homeo-keycloak:
    image: quay.io/keycloak/keycloak:22.0.4
    container_name: homeo-keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL_HOST=homeo-postgres
      - KC_DB_URL_DATABASE=keycloak
      - KC_DB_USERNAME=postgres
      - KC_DB_PASSWORD=password
    ports:
      - 8079:8080
    command: start-dev
    depends_on:
      - homeo-postgres

volumes:
  homeo-postgres:
