name: CategoryService CI

on:
  push:
    branches: [ "main", "dev" ]
    paths: [ "CategoryService/**" ]
  pull_request:
    branches: [ "main", "dev" ]
    paths: [ "CategoryService/**" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
      
    - name: Grant execute permission to gradlew
      run: chmod +x CategoryService/gradlew
      
    - name: Run build with Gradle Wrapper
      run: cd CategoryService && ./gradlew build
