name: UserService CI

on:
  push:
    branches: [ "main", "dev" ]
    paths: [ "UserService/**" ]
  pull_request:
    branches: [ "main", "dev" ]
    paths: [ "UserService/**" ]

permissions:
  contents: read

env:
  OKTA_API_ISSUER: ${{ secrets.OKTA_API_ISSUER }}
  OKTA_API_AUDIENCE: ${{ secrets.OKTA_API_AUDIENCE }}
  OKTA_API_DOMAIN: ${{ secrets.OKTA_API_DOMAIN }}
  OKTA_MTM_CLIENT_ID: ${{ secrets.OKTA_MTM_CLIENT_ID }}
  OKTA_MTM_CLIENT_SECRET: ${{ secrets.OKTA_MTM_CLIENT_SECRET }}
  OKTA_MANAGEMENT_API_AUDIENCE: ${{ secrets.OKTA_MANAGEMENT_API_AUDIENCE }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Run build with Gradle Wrapper
      run: ./gradlew build
